### ISSUE TITLE
App with Wordpair generation

### ISSUE THREAD

**Issue by temple** [ProWeb21/Dart-00-State-sharing#1]
## GOAL
As a user, I want to generate random word pairs so I can see them on the App and be able to ask for another one.

### TASKS
- [ ] Create an App
- [ ] Add a page with a button and a banner
- [ ] Create an App State with the current word pair
- [ ] Make the banner watch the App State's current word pair
- [ ] Create a method to generate a new Word Pair
- [ ] Make the button invoke the generation method when pressed
