### ISSUE TITLE
"Toggle Wordpair as favorite" feature

### ISSUE THREAD

**Issue by temple** [ProWeb21/Dart-00-State-sharing#3]
## GOAL
As a user, I want to toggle the word pair I am seeing as a favorite or non favorite word pair.

### TASKS
- [ ] Add a "toggle favorite" button beside the `Next` one
- [ ] Add favorites list and a method toggle in the App State 
- [ ] Make the button invoke the toggle method passing the current Word Pair
- [ ] Make the button icon depend on the status of the Word Pair (favorite or not)
