### ISSUE TITLE
Favorites screen

### ISSUE THREAD

**Issue by temple** [ProWeb21/Dart-00-State-sharing#5]
## GOAL
As a user, I want to list my favorite word pairs so I can remove them from my favorites list.

### TASKS
- [ ] Create a side navigation panel with Home and Favorites icons
- [ ] Create a new Favorite Screen with a list
- [ ] Connect the list with the favorites
- [ ] Make each favorite wordpair removable
- [ ] Make the "Favorites" icon open the Favorite Screen when pressed
- [ ] Make the "Home" icon open the Main Page Screen (with banner an buttons) when pressed
